version: '3.9'

services:
  client:
    build: ./client
    ports:
      - '1234:80'
    stdin_open: true

  web:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - static:/static
 
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - static:/static
    depends_on:
      - web
volumes:
  static: