# Generated by Django 4.2.6 on 2023-10-06 08:54

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('embedding', pgvector.django.VectorField(dimensions=768)),
                ('document', models.CharField(blank=True)),
                ('convo_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'embedding',
            },
        ),
    ]
