# Generated by Django 4.2.6 on 2023-10-10 16:14

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=384),
        ),
    ]
