# Generated by Django 4.2.6 on 2023-10-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_embedding_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convo_id', models.CharField(max_length=100)),
                ('convo_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'conversation',
            },
        ),
    ]
